version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    build:
      context: .
    environment:
      DB_HOST: database
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/escola
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"

volumes:
  db-volume:
