version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola-prod
    volumes:
      - db-prod-volume:/var/lib/postgresql/data

  api:
    image: joaovrt/testedocker:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: escola-prod
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      - database

volumes:
  db-prod-volume:
